### ISSUE TITLE
Allow HTTP client to be swapped out to support browser usage

### ISSUE THREAD

**Issue by griest024** [scttcper/deluge#110]
I would like to use this lib in the browser. Could you allow another HTTP client to be used in place of got (like perhaps [ky](https://github.com/sindresorhus/ky)) so that browser usage is possible? I will write this, are you open to a PR?

**Comment by scttcper** [comment]
Hey sorry, no plans to move off got for now as its pretty good when you're doing backend stuff. your best bet is probably to fork and replace it with whatever you want

**Comment by griest024** [comment]
fair enough. [here is my feature branch for posterity](https://github.com/griest024/deluge/tree/feat/abstract-http-client)
